---

- name: lock root
  user:
    name: root
    password_lock: yes

- name: configure nathan
  user:
    name: nathan
    append: yes
    groups:
      - docker
    generate_ssh_key: yes
    ssh_key_bits: 2048

- name: enable ntp
  systemd:
    name: systemd-timesyncd
    enabled: yes
    state: started

- name: configure local hostname resolution
  copy:
    src: etc/nsswitch.conf
    dest: /etc/nsswitch.conf

- name: enable avahi
  systemd:
    name: avahi-daemon
    enabled: yes
    state: started

- name: configure X11 keymap
  copy:
    src: etc/X11/xorg.conf.d/00-keyboard.conf
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf

- name: configure X11 mouse config
  copy:
    src: etc/X11/xorg.conf.d/99-libinput-custom-config.conf
    dest: /etc/X11/xorg.conf.d/99-libinput-custom-config.conf

#- name: configure pacman
#  copy:
#    src: etc/pacman.conf
#    dest: /etc/pacman.conf

- name: setup nginx reverse proxy
  copy:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: configure samba share
  ansible.builtin.copy:
    src: etc/samba/smb.conf
    dest: /etc/samba/smb.conf
    mode: 0644

- name: enable samba
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - smb
    - nmb

