---

- hosts: dev
  roles: 
    - role: weareinteractive.sudo
      become: yes
      tags: 
        - provision-system
        - provision-sudo
    - role: arch
      become: yes
      tags: 
        - provision-system
        - provision-arch
    - role: system-config
      become: yes
      tags: 
        - provision-system
        - provision-config
    - role: user-config
      tags: 
        - provision-user
        - provision-config
