---

- hosts: dev
  roles: 
    - role: weareinteractive.sudo
      become: yes
      tags: 
        - system
        - sudo
    - role: arch
      become: yes
      tags: 
        - system
        - arch
    - role: system-config
      become: yes
      tags: 
        - system
        - config
    - role: user-config
      tags: 
        - user
        - config

- hosts: base
  roles:
    - role: setup
      become: yes
