---

- hosts: dev
  roles: 
    - role: weareinteractive.sudo
      become: yes
      tags: 
        - sudo
    - role: arch
      become: yes
      tags: 
        - arch
    - role: config
      become: yes
      tags: 
        - config
