---

- name: check default target
  command: systemctl get-default
  register: default_target

- name: set default target
  command: systemctl set-default graphical.target
  when: default_target.stdout != "graphical.target"

- name: configure lightdm-greeter
  copy:
    src: etc/lightdm/lightdm-gtk-greeter.conf
    dest: /etc/lightdm/lightdm-gtk-greeter.conf
    backup: true

- name: add lightdm display setup script
  copy:
    src: etc/lightdm/display_setup.sh
    dest: /etc/lightdm/display_setup.sh
    backup: true

- name: configure lightdm display setup script
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#display-setup-script='
    line: display-setup-script=/etc/lightdm/display_setup.sh
    backup: true

#- name: enable lightdm
#  systemd:
#    name: lightdm
#    enabled: yes

- name: copy vconsole.conf
  copy:
    src: etc/vconsole.conf
    dest: /etc/vconsole.conf
    backup: true

- name: configure tlp
  copy:
    src: "{{ item }}"
    dest: /etc/tlp.d/
    backup: true
  with_items:
    - etc/tlp.d/10-processor.conf
    - etc/tlp.d/20-battery-care.conf
