---

- name: run system upgrade
  pacman:
    update_cache: yes
    upgrade: yes


- name: install reflector
  pacman:
    name: reflector
    state: present

- name: configure reflector unit file
  copy:
    src: reflector.service
    dest: /etc/systemd/system/reflector.service
    mode: 0644

- name: create pacman hooks directory
  file:
    path: /etc/pacman.d/hooks
    state: directory
    mode: 0755

- name: configure reflector pacman hook
  copy:
    src: mirrorupgrade.hook
    dest: /etc/pacman.d/hooks/mirrorupgrade.hook
    mode: 0644

- name: run reflector
  systemd:
    name: reflector
    state: started
    daemon_reload: yes

- name: install pacman packages
  pacman:
    name: "{{ pacman_packages }}"
    state: present
