---

- name: lock root
  user:
    name: root
    password_lock: yes

- name: configure nathan
  user:
    name: nathan
    append: yes
    groups:
      - docker
    generate_ssh_key: yes
    ssh_key_bits: 2048
