---

- name: lock root
  user:
    name: root
    password_lock: yes

- name: configure nathan
  user:
    name: nathan
    append: yes
    groups:
      - docker
    generate_ssh_key: yes
    ssh_key_bits: 2048

- name: enable ntp
  systemd:
    name: systemd-timesyncd
    enabled: yes
    state: started

- name: configure X11 keymap
  copy:
    src: etc/X11/xorg.conf.d/00-keyboard.conf
    dest: etc/X11/xorg.conf.d/00-keyboard.conf
