---

- name: run reflector
  systemd:
    name: reflector
    state: started
    daemon_reload: yes

- name: enable tlp
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - tlp
    - tlp-sleep

# systemd-rfkill conflicts with tlp
# https://wiki.archlinux.org/index.php/TLP
- name: mask systemd-rfkill
  systemd:
    name: "{{ item }}"
    masked: yes
    enabled: no
    state: stopped
  loop:
    - systemd-rfkill.service
    - systemd-rfkill.socket

- name: enable redshift
  systemd:
    name: redshift
    scope: user
    state: started
    enabled: yes

- name: enable docker
  systemd:
    name: docker
    state: started
    enabled: yes
